= Scalable Task Processing Using a Shared Work Queue

:toc:

[options="header"]
|=== 
| ID | Short Name
| `200` | `shared-work-queue`
|===

== Description

This mission demonstrates how to dispatch tasks to a scalable set of
worker processes using a message queue.  It uses the AMQP 1.0 message
protocol to send and receive messages.  The workers are implemented in
a variety of different languages and application runtimes.

Having a single, well known shared resource for adding and consuming
work makes it easier to scale the number of workers up and down.  The
frontend process does not need to know any of the details of the
backend workers.  The use of a standard messaging protocol enables
frontends and workers written in any language to interoperate.

The mission covers:

* Sending work requests to a common work queue
* Receiving and processing work requests as they come in
* Sending the processed result back to the requesting process
* Adding new workers as demand increases or removing workers as it dies down
* Monitoring the status of the worker processes

== User Problem

The user has a large number of discrete tasks that require processing.
To make sure they are processed with satisfactory speed, the user
wants to be able to add worker processes on demand as the number of
outstanding tasks grow.

One could achieve this by telling every requesting process about every
worker process, but that requires updating many potential requesters.
Instead, the user wants to design the system so that the requester
does not need to know how many workers there are, and the workers do
not need to know which process the request came from.

== Concepts and Architectural Patterns

* Sending and receiving messages.  The application uses the AMQP
  message protocol to communicate using queues and topics on a message
  server.

* Sending request messages and receiving response messages.  The
  application demonstrates how the request-response messaging pattern
  is implemented in AMQP.

* Periodically sending broadcast updates.  The application
  demonstrates use of the publish-subscribe messaging pattern for
  distributing information to multiple consumers.

* Maintaining connections between services.  The frontend and backend
  components reconnect to the message server if the connection is
  lost.

* Scaling backend workers up and down.  The operator can freely add
  and remove backend workers.

== Prerequisites

* The user has access to an OpenShift instance and is logged in.

* The user has selected a project in which the frontend and backend
  processes will be deployed.

* The user's project has an instance of AMQ Broker installed and
  running.  The backend and frontend processes have permission to
  connect to the broker.

* The broker has a queue named `upstate/requests`.  The frontend and
  backend processes can send and receive messages there.

* The broker has a topic named `upstate/worker-status`.  The frontend
  and backend processes can send and receive messages there.

== Use Case

This mission demonstrates a distributed messaging application.  It
contains multiple components that communicate using a messaging
server.

The frontend, a web server in this case, registers requests to perform
work by sending a request message to a well known queue.  A backend
worker then fetches the work request from the queue and performs the
work.

When the frontend creates the request message, it also establishes a
dedicated queue for responses.  It includes the server-generated
address of this queue in its request.  After processing the work, the
backend worker sends the result as a response to the pre-established
response queue.

XXX

// Scaling the number of workers

== Acceptance Criteria

XXX

=== Vert.x-specific Acceptance Criteria

XXX

=== Swarm-specific Acceptance Criteria

XXX

=== Boot-specific Acceptance Criteria

XXX

=== Node.js Acceptance Criteria

XXX

== Integration Requirements

== Tags

== Notes

Demo code - <https://github.com/ssorj/upstate>

== Approval
|=======
|PM|https://github.com/<username>[Name]|&#x2611;
|DevExp|https://github.com/<username>[Name]|&#x2611;
|Vert.x|Clement|&#x2611;
|WildFly Swarm|https://github.com/<username>[Name]|&#x2611;
|Spring Boot|https://github.com/<username>[Name]|&#x2611;
|Node.js|https://github.com/<username>[Name]|&#x2611;
|QE|https://github.com/<username>[Name]|&#x2611;
|Docs|https://github.com/<username>[Name]|&#x2611;
|Architect|https://github.com/<username>[Name]|&#x2610;
|=======

// unchecked = &#x2610;
// checked = &#x2611;
